## Name:Aastha Pusdekar
## Class:B-B4
## Roll No:52
## ML LAB 7

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (accuracy_score,precision_score,recall_score,
                             f1_score, confusion_matrix, classification_report,
                             ConfusionMatrixDisplay)
pd.set_option('display.max_columns',None)

In [ ]:
from google.colab import files
import io

print("Please select and upload your 'Raisin_Dataset.xlsx' file:")
uploaded = files.upload()

Please select and upload your 'Raisin_Dataset.xlsx' file:

Saving Raisin_Dataset.xlsx to Raisin_Dataset (1).xlsx

In [ ]:
# Read the uploaded Excel file into the 'df' DataFrame
df = pd.read_excel('Raisin_Dataset.xlsx')

# Display the first few rows of the dataset
df.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,Kecimen
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,Kecimen
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,Kecimen

In [ ]:
df.tail()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
895,83248,430.077308,247.838695,0.817263,85839,0.668793,1129.072,Besni
896,87350,440.735698,259.293149,0.808629,90899,0.636476,1214.252,Besni
897,99657,431.706981,298.837323,0.721684,106264,0.741099,1292.828,Besni
898,93523,476.344094,254.176054,0.845739,97653,0.658798,1258.548,Besni
899,85609,512.081774,215.271976,0.907345,89197,0.632020,1272.862,Besni

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Area             900 non-null    int64
 1   MajorAxisLength  900 non-null    float64
 2   MinorAxisLength  900 non-null    float64
 3   Eccentricity     900 non-null    float64
 4   ConvexArea       900 non-null    int64
 5   Extent           900 non-null    float64
 6   Perimeter        900 non-null    float64
 7   Class            900 non-null    object
dtypes: float64(5), int64(2), object(1)
memory usage: 56.4+ KB

In [ ]:
df.describe()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
count,900.000000,900.000000,900.000000,900.000000,900.000000,900.000000,900.000000
mean,87804.127778,430.929950,254.488133,0.781542,91186.090000,0.699508,1165.906636
std,39002.111390,116.035121,49.988902,0.090318,40769.290132,0.053468,273.764315
min,25387.000000,225.629541,143.710872,0.348730,26139.000000,0.379856,619.074000
25%,59348.000000,345.442898,219.111126,0.741766,61513.250000,0.670869,966.410750
50%,78902.000000,407.803951,247.848409,0.798846,81651.000000,0.707367,1119.509000
75%,105028.250000,494.187014,279.888575,0.842571,108375.750000,0.734991,1308.389750
max,235047.000000,997.291941,492.275279,0.962124,278217.000000,0.835455,2697.753000

In [ ]:
df.shape

(900, 8)

In [ ]:
df.columns

Index(['Area', 'MajorAxisLength', 'MinorAxisLength', 'Eccentricity',
       'ConvexArea', 'Extent', 'Perimeter', 'Class'],
      dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Area               0
MajorAxisLength    0
MinorAxisLength    0
Eccentricity       0
ConvexArea         0
Extent             0
Perimeter          0
Class              0
dtype: int64

In [ ]:
df.dtypes

Area                 int64
MajorAxisLength    float64
MinorAxisLength    float64
Eccentricity       float64
ConvexArea           int64
Extent             float64
Perimeter          float64
Class               object
dtype: object

In [ ]:
#barplot,piechart,histogram,boxplot histogram with kde, heatmap,scatterplot

In [ ]:
label_encoder=LabelEncoder()
df['Class_encoded']=label_encoder.fit_transform(df['Class'])

In [ ]:
print(df[["Class","Class_encoded"]].head(5))

     Class  Class_encoded
0  Kecimen              1
1  Kecimen              1
2  Kecimen              1
3  Kecimen              1
4  Kecimen              1

In [ ]:
numerical_features=df.select_dtypes(include=np.number).columns

In [ ]:
X=df[numerical_features]
y=df['Class_encoded']
print(X.shape)
print(y.shape)

(900, 8)
(900,)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print("Training Samples", X_train.shape[0])
print("Testing Samples",X_test.shape[0])

Training Samples 720
Testing Samples 180

In [ ]:
GaussianNB()

GaussianNB()

In [ ]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(X_test)
print(y_pred)

[1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1
 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1
 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1]

In [ ]:
comparison=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
print(comparison.head(5))

     Actual  Predicted
502       0          1
637       0          0
701       0          0
237       1          1
707       0          0

In [ ]:
comparison["Actual_Class"] = label_encoder.inverse_transform(comparison["Actual"])
comparison["Predicted_Class"] = label_encoder.inverse_transform(comparison["Predicted"])
comparison.head(5)

     Actual  Predicted Actual_Class Predicted_Class
502       0          1        Besni         Kecimen
637       0          0        Besni           Besni
701       0          0        Besni           Besni
237       1          1      Kecimen         Kecimen
707       0          0        Besni           Besni

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)
print("Accuracy(%)",accuracy*100)

Accuracy: 0.8277777777777777
Accuracy(%) 82.77777777777777

In [ ]:
precision_score=precision_score(y_test,y_pred)
print("Precision:",precision_score)

Precision: 0.7657657657657657

In [ ]:
recall_score=recall_score(y_test,y_pred)
print("Recall:",recall_score)

Recall: 0.9444444444444444

In [ ]:
f1=f1_score(y_test,y_pred)
print("F1 Score:",f1)

F1 Score: 0.845771144278607

In [ ]:
print("=====Model Performance====")
print(f"Accuracy:{accuracy:.4f}%")
print(f"Precision:{precision_score:4f}%")
print(f"Recall:{recall_score:4f}%")
print(f"F1 Score:{f1:4f}%")

=====Model Performance====
Accuracy:0.8278%
Precision:0.765766%
Recall:0.944444%
F1 Score:0.845771%

In [ ]:
print("Classification Report:\n")
print(classification_report(y_test,y_pred,target_names=label_encoder.classes_))

Classification Report:

              precision    recall  f1-score   support

       Besni       0.93      0.71      0.81        90
     Kecimen       0.77      0.94      0.85        90

    accuracy                           0.83       180
   macro avg       0.85      0.83      0.83       180
weighted avg       0.85      0.83      0.83       180

In [ ]:
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[64 26]
 [ 5 85]]

In [ ]:
from sklearn.metrics import accuracy_score
y_train_pred=gnb.predict(X_train)
y_test_pred=gnb.predict(X_test)
train_accuracy=accuracy_score(y_train,y_train_pred)
test_accuracy=accuracy_score(y_test,y_test_pred)
print("Training Accuracy:",train_accuracy)
print("Testing Accuracy:",test_accuracy)

Training Accuracy: 0.8375
Testing Accuracy: 0.8277777777777777

In [ ]:
GaussianNB(priors=None)

GaussianNB()